---
title: "Summary Statistics"
output: html_document
---

```{r}
library(tidyverse)
```


```{r}


# This function calculates summary statistics for allele frequencies at the
# final generation across all simulations.
# Inputs: results = data frame from run_simulations() containing generation,
#         allele, frequency, and simulation columns
# Outputs: a summarized data frame with one row per allele showing
#          mean, standard deviation, fixation rate, and loss rate of final generation
summary_stats <- function(results) {
  results %>%
    filter(generation == max(generation)) %>% #keeps only the last generation from all simulation runs
    group_by(allele) %>% #splits data into the 3 groups of alleles (brown, blue, green)
    summarise(
      Mean_Final_Frequency = round(mean(frequency), 4), #The average ending frequency across all simulations
      SD_Final_Frequency = round(sd(frequency), 4), #how much the ending frequency varied between simulations
      Fixation_Rate = round(mean(frequency == 1.0), 4), #the proportion of simulations where an allele reached a frequency  of 1.0 (meaning it took over completely)
      Loss_Rate = round(mean(frequency == 0.0), 4) #the proportion of simulations where an allele hit 0.0 frequency (meaning it died out/went extinct)
    )
}
```


